ALTER TABLE organizations
    ADD COLUMN IF NOT EXISTS license_key_hash CHAR(64) UNIQUE,
    ADD COLUMN IF NOT EXISTS license_key_prefix VARCHAR(32),
    ADD COLUMN IF NOT EXISTS license_started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS license_expires_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS notes TEXT;

